/**
 * Lista de respostas do MODO DIFÍCIL.
 *
 * ⚠️  Mesma regra de `words.ts`: NUNCA importe daqui de dentro de `app/`.
 *     `npm run check:leak` varre o bundle atrás destas chaves também.
 *
 * O que muda em relação a `words.ts` é o comprimento: aqui as chaves têm de 6
 * a 8 letras, e é a palavra do dia que define a largura do tabuleiro — não há
 * um número fixo. Por isso a lista precisa ficar equilibrada entre os três
 * tamanhos, senão o modo vira "quase sempre 8 letras"; há teste para isso.
 */
import type { Entry } from './words'

export const WORDS_HARD: Entry[] = [
  { word: 'ESTOLA', key: 'ESTOLA', definition: 'Faixa de tecido sobre a alva, sinal do ministério' },
  { word: 'CASULA', key: 'CASULA', definition: 'Veste de cima de quem preside a Eucaristia' },
  { word: 'CÁLICE', key: 'CALICE', definition: 'Taça que recebe o vinho da consagração' },
  { word: 'PATENA', key: 'PATENA', definition: 'Prato raso que recebe o pão' },
  { word: 'HÓSTIA', key: 'HOSTIA', definition: 'Pão ázimo preparado para a comunhão' },
  { word: 'BÁCULO', key: 'BACULO', definition: 'Bastão de pastor, insígnia do bispo' },
  { word: 'CRIPTA', key: 'CRIPTA', definition: 'Câmara abaixo do altar, onde repousam relíquias' },
  { word: 'ÁBSIDE', key: 'ABSIDE', definition: 'Fundo semicircular da igreja, atrás do altar' },
  { word: 'ERMIDA', key: 'ERMIDA', definition: 'Capela isolada, longe do povoado' },
  { word: 'ABADIA', key: 'ABADIA', definition: 'Mosteiro governado por um abade' },
  { word: 'SÍNODO', key: 'SINODO', definition: 'Assembleia que delibera sobre a vida da Igreja' },
  { word: 'CABIDO', key: 'CABIDO', definition: 'O colégio de cônegos de uma catedral' },
  { word: 'NOVIÇO', key: 'NOVICO', definition: 'Quem cumpre o tempo de prova antes dos votos' },
  { word: 'MÁRTIR', key: 'MARTIR', definition: 'Testemunha que selou a fé com o próprio sangue' },
  { word: 'LAVABO', key: 'LAVABO', definition: 'Rito de lavar as mãos antes da oração eucarística' },
  { word: 'OITAVA', key: 'OITAVA', definition: 'Os oito dias em que uma festa se prolonga' },
  { word: 'LAUDES', key: 'LAUDES', definition: 'A oração da manhã, com o cântico de Zacarias' },
  { word: 'MISSAL', key: 'MISSAL', definition: 'Livro que reúne os textos da missa' },
  { word: 'NARTEX', key: 'NARTEX', definition: 'Vestíbulo da igreja antiga, lugar dos catecúmenos' },
  { word: 'VITRAL', key: 'VITRAL', definition: 'Janela de vidros coloridos, que ensina pela luz' },
  { word: 'TRÍDUO', key: 'TRIDUO', definition: 'Os três dias santos, da Ceia à Vigília' },
  { word: 'CINZAS', key: 'CINZAS', definition: 'Impostas na quarta-feira que abre a Quaresma' },
  { word: 'BÊNÇÃO', key: 'BENCAO', definition: 'Palavra que consagra e envia' },
  { word: 'NAVETA', key: 'NAVETA', definition: 'Pequeno recipiente que guarda o incenso' },
  { word: 'ACÓLITO', key: 'ACOLITO', definition: 'Quem serve ao altar, levando luz e livro' },
  { word: 'CHANTRE', key: 'CHANTRE', definition: 'Quem entoa e conduz o canto no coro' },
  { word: 'GRADUAL', key: 'GRADUAL', definition: 'Salmo cantado entre as leituras' },
  { word: 'ALELUIA', key: 'ALELUIA', definition: 'Aclamação antes do Evangelho, calada na Quaresma' },
  { word: 'SANCTUS', key: 'SANCTUS', definition: '"Santo, santo, santo", com que se entra no Cânon' },
  { word: 'VIÁTICO', key: 'VIATICO', definition: 'A comunhão levada a quem está de partida' },
  { word: 'MATINAS', key: 'MATINAS', definition: 'O ofício da madrugada, o mais longo do dia' },
  { word: 'VIGÍLIA', key: 'VIGILIA', definition: 'Noite de espera, como a que precede a Páscoa' },
  { word: 'RUBRICA', key: 'RUBRICA', definition: 'Instrução em vermelho, que diz como celebrar' },
  { word: 'PRÓPRIO', key: 'PROPRIO', definition: 'Os textos que só servem àquele dia' },
  { word: 'DIÁCONO', key: 'DIACONO', definition: 'Ministro do serviço, que proclama o Evangelho' },
  { word: 'VIGÁRIO', key: 'VIGARIO', definition: 'Quem faz as vezes de outro no governo pastoral' },
  { word: 'DIOCESE', key: 'DIOCESE', definition: 'Porção do povo de Deus confiada a um bispo' },
  { word: 'CÁTEDRA', key: 'CATEDRA', definition: 'Assento do bispo, que dá nome à catedral' },
  { word: 'CIBÓRIO', key: 'CIBORIO', definition: 'Vaso com tampa que guarda as hóstias' },
  { word: 'SUDÁRIO', key: 'SUDARIO', definition: 'Pano que cobriu o rosto no sepulcro' },
  { word: 'INCENSO', key: 'INCENSO', definition: 'Fumo que sobe como a oração dos justos' },
  { word: 'POBREZA', key: 'POBREZA', definition: 'Um dos votos da vida religiosa' },
  { word: 'JUBILEU', key: 'JUBILEU', definition: 'Ano de graça, de perdão e de recomeço' },
  { word: 'BATISMO', key: 'BATISMO', definition: 'Sacramento da água e do Espírito' },
  { word: 'ROMARIA', key: 'ROMARIA', definition: 'Caminhada de fé até um santuário' },
  { word: 'ANTÍFONA', key: 'ANTIFONA', definition: 'Verso que emoldura o salmo, antes e depois' },
  { word: 'SALTÉRIO', key: 'SALTERIO', definition: 'O livro dos salmos, repartido pelas horas' },
  { word: 'INTROITO', key: 'INTROITO', definition: 'Canto de entrada, que abre a celebração' },
  { word: 'PREFÁCIO', key: 'PREFACIO', definition: 'Louvor que conduz ao Sanctus' },
  { word: 'LADAINHA', key: 'LADAINHA', definition: 'Súplica em série, com resposta repetida' },
  { word: 'TURÍBULO', key: 'TURIBULO', definition: 'Vaso suspenso em que se queima o incenso' },
  { word: 'CUSTÓDIA', key: 'CUSTODIA', definition: 'Peça que expõe o Santíssimo à adoração' },
  { word: 'SACRÁRIO', key: 'SACRARIO', definition: 'Onde se reserva o pão consagrado' },
  { word: 'CORPORAL', key: 'CORPORAL', definition: 'Pano branco estendido sob o cálice' },
  { word: 'RELÍQUIA', key: 'RELIQUIA', definition: 'Resto venerado de um santo ou da cruz' },
  { word: 'QUARESMA', key: 'QUARESMA', definition: 'Os quarenta dias de preparação para a Páscoa' },
  { word: 'EPIFANIA', key: 'EPIFANIA', definition: 'Manifestação do Senhor às nações' },
  { word: 'ASCENSÃO', key: 'ASCENSAO', definition: 'Quarenta dias depois da Páscoa' },
  { word: 'CENÁCULO', key: 'CENACULO', definition: 'Sala alta da Última Ceia e de Pentecostes' },
  { word: 'SEPULCRO', key: 'SEPULCRO', definition: 'Túmulo novo, que amanheceu vazio' },
  { word: 'CONCÍLIO', key: 'CONCILIO', definition: 'Assembleia que define a fé da Igreja' },
  { word: 'PARÓQUIA', key: 'PAROQUIA', definition: 'Comunidade estável confiada a um pároco' },
  { word: 'LITURGIA', key: 'LITURGIA', definition: '"Obra do povo": o culto público da Igreja' },
  { word: 'COMUNHÃO', key: 'COMUNHAO', definition: 'Participação no Corpo e no Sangue' },
  { word: 'CLAUSURA', key: 'CLAUSURA', definition: 'A parte do mosteiro reservada à comunidade' },
  { word: 'CAPÍTULO', key: 'CAPITULO', definition: 'Reunião diária em que se lê a Regra' },
  { word: 'EXÉQUIAS', key: 'EXEQUIAS', definition: 'O ofício da Igreja pelos seus mortos' },
  { word: 'RESPONSO', key: 'RESPONSO', definition: 'Canto de resposta, sobretudo pelos defuntos' },
  { word: 'ASPERSÃO', key: 'ASPERSAO', definition: 'Rito de aspergir a assembleia com água' },
]
