/**
 * Lista de respostas do Ordle.
 *
 * ⚠️  NUNCA importe este arquivo de um composable, component ou page.
 *     Se ele entrar no bundle do client, a resposta do dia vaza.
 *     Depois de buildar: `grep -ril "AMBAO" .output/public/` tem que voltar vazio.
 *
 * `key`  — forma normalizada (sem acento, maiúscula), usada em toda comparação
 * `word` — grafia acentuada, só aparece no reveal
 */
export type Entry = { word: string; key: string; definition: string }

export const WORDS: Entry[] = [
  { word: 'MISSA', key: 'MISSA', definition: 'Celebração da Eucaristia' },
  { word: 'SALMO', key: 'SALMO', definition: 'Cântico do saltério, coração do Ofício Diário' },
  { word: 'CREDO', key: 'CREDO', definition: 'Símbolo da fé, niceno ou apostólico' },
  { word: 'ALTAR', key: 'ALTAR', definition: 'Mesa da Ceia do Senhor' },
  { word: 'AMBÃO', key: 'AMBAO', definition: 'Estante elevada de onde se proclamam as leituras' },
  { word: 'MITRA', key: 'MITRA', definition: 'Insígnia de cabeça do bispo' },
  { word: 'PRECE', key: 'PRECE', definition: 'Súplica breve, geralmente dialogada' },
  { word: 'SANTO', key: 'SANTO', definition: 'Aclamação do Sanctus; também o fiel canonizado' },
  { word: 'NATAL', key: 'NATAL', definition: 'Festa da Natividade do Senhor' },
  { word: 'CINZA', key: 'CINZA', definition: 'Quarta-feira que abre a Quaresma' },
  { word: 'RAMOS', key: 'RAMOS', definition: 'Domingo da entrada em Jerusalém' },
  { word: 'ÍCONE', key: 'ICONE', definition: 'Imagem sagrada da tradição oriental' },
  { word: 'CÍRIO', key: 'CIRIO', definition: 'Vela pascal acesa na Vigília' },
  { word: 'AMITO', key: 'AMITO', definition: 'Pano de linho usado sob a alva' },
  { word: 'MANTO', key: 'MANTO', definition: 'Veste ampla de cerimônia' },
  { word: 'LEIGO', key: 'LEIGO', definition: 'Fiel não ordenado' },
  { word: 'BISPO', key: 'BISPO', definition: 'Ministro que preside a diocese' },
  { word: 'PADRE', key: 'PADRE', definition: 'Presbítero' },
  { word: 'CLERO', key: 'CLERO', definition: 'Conjunto dos ordenados' },
  { word: 'CÚRIA', key: 'CURIA', definition: 'Órgão administrativo de uma diocese' },
  { word: 'TRONO', key: 'TRONO', definition: 'Cátedra do bispo na catedral' },
  { word: 'HINOS', key: 'HINOS', definition: 'Cânticos de louvor do Ofício' },
  { word: 'FONTE', key: 'FONTE', definition: 'Pia batismal' },
  { word: 'UNÇÃO', key: 'UNCAO', definition: 'Rito de ungir com óleo' },
  { word: 'GRAÇA', key: 'GRACA', definition: 'Favor imerecido de Deus' },
  { word: 'CULPA', key: 'CULPA', definition: 'Reconhecimento do pecado na confissão' },
  { word: 'JEJUM', key: 'JEJUM', definition: 'Abstinência penitencial' },
  { word: 'VOTOS', key: 'VOTOS', definition: 'Promessas solenes' },
  { word: 'ORDEM', key: 'ORDEM', definition: 'Sacramento da ordenação; também regra religiosa' },
  { word: 'REGRA', key: 'REGRA', definition: 'Norma de vida comunitária' },
  { word: 'ABADE', key: 'ABADE', definition: 'Superior de um mosteiro' },
  { word: 'MONGE', key: 'MONGE', definition: 'Religioso de vida contemplativa' },
  { word: 'SEXTA', key: 'SEXTA', definition: 'Hora menor rezada ao meio-dia' },
  { word: 'TERÇA', key: 'TERCA', definition: 'Hora menor rezada em meados da manhã' },
  { word: 'CÂNON', key: 'CANON', definition: 'Regra; também a oração eucarística' },
  { word: 'DOGMA', key: 'DOGMA', definition: 'Verdade de fé definida' },
  { word: 'CISMA', key: 'CISMA', definition: 'Ruptura da comunhão eclesial' },
  { word: 'ÁTRIO', key: 'ATRIO', definition: 'Pátio de entrada da igreja' },
  { word: 'PRIOR', key: 'PRIOR', definition: 'Superior de uma casa religiosa' },
  { word: 'ÊXODO', key: 'EXODO', definition: 'Livro da saída do Egito' },
  { word: 'KYRIE', key: 'KYRIE', definition: 'Súplica "Senhor, tem piedade"' },
  { word: 'AGNUS', key: 'AGNUS', definition: '"Cordeiro de Deus", cantado à fração do pão' },
  { word: 'SINAL', key: 'SINAL', definition: 'Gesto da cruz' },
  { word: 'CORAL', key: 'CORAL', definition: 'Grupo que canta a liturgia' },
  { word: 'ÓRGÃO', key: 'ORGAO', definition: 'Instrumento tradicional do culto' },
  { word: 'SINOS', key: 'SINOS', definition: 'Chamam à oração e marcam as horas' },
  { word: 'CULTO', key: 'CULTO', definition: 'Ato público de adoração' },
  { word: 'VINHO', key: 'VINHO', definition: 'Matéria eucarística com o pão' },
  { word: 'PÁLIA', key: 'PALIA', definition: 'Pequena cobertura rígida do cálice' },
  { word: 'PÁLIO', key: 'PALIO', definition: 'Faixa de lã concedida a arcebispos' },
  { word: 'CORPO', key: 'CORPO', definition: '"Corpo de Cristo", na comunhão' },
  { word: 'CANTO', key: 'CANTO', definition: 'Melodia própria da liturgia' },
  { word: 'SALVE', key: 'SALVE', definition: 'Antífona mariana do fim do dia' },
  { word: 'FÉRIA', key: 'FERIA', definition: 'Dia sem festa própria no calendário' },
  { word: 'VELAS', key: 'VELAS', definition: 'Luzes do altar' },
  { word: 'LINHO', key: 'LINHO', definition: 'Tecido das alfaias e vestes' },
  { word: 'CAPUZ', key: 'CAPUZ', definition: 'Parte do hábito monástico' },
  { word: 'NIMBO', key: 'NIMBO', definition: 'Auréola em torno da cabeça, na iconografia' },
  { word: 'MAGOS', key: 'MAGOS', definition: 'Visitantes do Oriente, na Epifania' },
  { word: 'LENHO', key: 'LENHO', definition: 'Madeira da cruz' },
  { word: 'PALMA', key: 'PALMA', definition: 'Ramo bento do Domingo de Ramos' },
  { word: 'PEDRO', key: 'PEDRO', definition: 'Apóstolo, festa em 29 de junho' },
  { word: 'PAULO', key: 'PAULO', definition: 'Apóstolo dos gentios' },
  { word: 'ANDRÉ', key: 'ANDRE', definition: 'Apóstolo, festa em 30 de novembro' },
  { word: 'TIAGO', key: 'TIAGO', definition: 'Apóstolo, festa em 25 de julho' },
  { word: 'LUCAS', key: 'LUCAS', definition: 'Evangelista, festa em 18 de outubro' },
  { word: 'MARIA', key: 'MARIA', definition: 'Mãe do Senhor' },
  { word: 'SIMÃO', key: 'SIMAO', definition: 'Apóstolo, festa em 28 de outubro' },
  { word: 'RITOS', key: 'RITOS', definition: 'Formas fixas da celebração' },
]
