/**
 * Lista de respostas do Ordle.
 *
 * ⚠️  NUNCA importe este arquivo de um composable, component ou page.
 *     Se ele entrar no bundle do client, a resposta do dia vaza.
 *     Depois de buildar: `grep -ril "AMBAO" .output/public/` tem que voltar vazio.
 *
 * `key`  — forma normalizada (sem acento, maiúscula), usada em toda comparação
 * `word` — grafia acentuada, só aparece no reveal
 */
export type Entry = { word: string; key: string; definition: string }

export const WORDS: Entry[] = [
  { word: 'MISSA', key: 'MISSA', definition: 'Celebração da Eucaristia' },
  { word: 'SALMO', key: 'SALMO', definition: 'Cântico do saltério, coração do Ofício Diário' },
  { word: 'CREDO', key: 'CREDO', definition: 'Símbolo da fé, niceno ou apostólico' },
  { word: 'ALTAR', key: 'ALTAR', definition: 'Mesa da Ceia do Senhor' },
  { word: 'AMBÃO', key: 'AMBAO', definition: 'Estante elevada de onde se proclamam as leituras' },
  { word: 'MITRA', key: 'MITRA', definition: 'Insígnia de cabeça do bispo' },
  { word: 'PRECE', key: 'PRECE', definition: 'Súplica breve, geralmente dialogada' },
  { word: 'SANTO', key: 'SANTO', definition: 'Aclamação do Sanctus; também o fiel canonizado' },
  { word: 'NATAL', key: 'NATAL', definition: 'Festa da Natividade do Senhor' },
  { word: 'CINZA', key: 'CINZA', definition: 'Quarta-feira que abre a Quaresma' },
  { word: 'RAMOS', key: 'RAMOS', definition: 'Domingo da entrada em Jerusalém' },
  { word: 'ÍCONE', key: 'ICONE', definition: 'Imagem sagrada da tradição oriental' },
  { word: 'CÍRIO', key: 'CIRIO', definition: 'Vela pascal acesa na Vigília' },
  { word: 'AMITO', key: 'AMITO', definition: 'Pano de linho usado sob a alva' },
  { word: 'MANTO', key: 'MANTO', definition: 'Veste ampla de cerimônia' },
  { word: 'LEIGO', key: 'LEIGO', definition: 'Fiel não ordenado' },
  { word: 'BISPO', key: 'BISPO', definition: 'Ministro que preside a diocese' },
  { word: 'PADRE', key: 'PADRE', definition: 'Presbítero' },
  { word: 'CLERO', key: 'CLERO', definition: 'Conjunto dos ordenados' },
  { word: 'CÚRIA', key: 'CURIA', definition: 'Órgão administrativo de uma diocese' },
  { word: 'TRONO', key: 'TRONO', definition: 'Cátedra do bispo na catedral' },
  { word: 'HINOS', key: 'HINOS', definition: 'Cânticos de louvor do Ofício' },
  { word: 'FONTE', key: 'FONTE', definition: 'Pia batismal' },
  { word: 'UNÇÃO', key: 'UNCAO', definition: 'Rito de ungir com óleo' },
  { word: 'GRAÇA', key: 'GRACA', definition: 'Favor imerecido de Deus' },
  { word: 'CULPA', key: 'CULPA', definition: 'Reconhecimento do pecado na confissão' },
  { word: 'JEJUM', key: 'JEJUM', definition: 'Abstinência penitencial' },
  { word: 'VOTOS', key: 'VOTOS', definition: 'Promessas solenes' },
  { word: 'ORDEM', key: 'ORDEM', definition: 'Sacramento da ordenação; também regra religiosa' },
  { word: 'REGRA', key: 'REGRA', definition: 'Norma de vida comunitária' },
  { word: 'ABADE', key: 'ABADE', definition: 'Superior de um mosteiro' },
  { word: 'MONGE', key: 'MONGE', definition: 'Religioso de vida contemplativa' },
  { word: 'SEXTA', key: 'SEXTA', definition: 'Hora menor do Ofício, ao meio-dia' },
  { word: 'TERÇA', key: 'TERCA', definition: 'Hora menor do Ofício, em meados da manhã' },
  { word: 'CÂNON', key: 'CANON', definition: 'Regra; também a oração eucarística' },
  { word: 'DOGMA', key: 'DOGMA', definition: 'Verdade de fé definida' },
  { word: 'CISMA', key: 'CISMA', definition: 'Ruptura da comunhão eclesial' },
  { word: 'ÁTRIO', key: 'ATRIO', definition: 'Pátio de entrada da igreja' },
  { word: 'PRIOR', key: 'PRIOR', definition: 'Superior de uma casa religiosa' },
  { word: 'ÊXODO', key: 'EXODO', definition: 'Livro da saída do Egito' },
  { word: 'KYRIE', key: 'KYRIE', definition: 'Súplica "Senhor, tem piedade"' },
  { word: 'AGNUS', key: 'AGNUS', definition: '"Cordeiro de Deus", cantado à fração do pão' },
  { word: 'SINAL', key: 'SINAL', definition: 'Gesto da cruz' },
  { word: 'CORAL', key: 'CORAL', definition: 'Grupo que canta a liturgia' },
  { word: 'ÓRGÃO', key: 'ORGAO', definition: 'Instrumento tradicional do culto' },
  { word: 'SINOS', key: 'SINOS', definition: 'Chamam à oração e marcam as horas' },
  { word: 'CULTO', key: 'CULTO', definition: 'Ato público de adoração' },
  { word: 'VINHO', key: 'VINHO', definition: 'Matéria eucarística com o pão' },
  { word: 'PÁLIA', key: 'PALIA', definition: 'Pequena cobertura rígida do cálice' },
  { word: 'PÁLIO', key: 'PALIO', definition: 'Faixa de lã concedida a arcebispos' },
  { word: 'CORPO', key: 'CORPO', definition: '"Corpo de Cristo", na comunhão' },
  { word: 'CANTO', key: 'CANTO', definition: 'Melodia própria da liturgia' },
  { word: 'SALVE', key: 'SALVE', definition: 'Antífona mariana do fim do dia' },
  { word: 'FÉRIA', key: 'FERIA', definition: 'Dia sem festa própria no calendário' },
  { word: 'VELAS', key: 'VELAS', definition: 'Luzes do altar' },
  { word: 'LINHO', key: 'LINHO', definition: 'Tecido das alfaias e vestes' },
  { word: 'CAPUZ', key: 'CAPUZ', definition: 'Parte do hábito monástico' },
  { word: 'NIMBO', key: 'NIMBO', definition: 'Auréola em torno da cabeça, na iconografia' },
  { word: 'MAGOS', key: 'MAGOS', definition: 'Visitantes do Oriente, na Epifania' },
  { word: 'LENHO', key: 'LENHO', definition: 'Madeira da cruz' },
  { word: 'PALMA', key: 'PALMA', definition: 'Ramo bento do Domingo de Ramos' },
  { word: 'PEDRO', key: 'PEDRO', definition: 'Apóstolo, festa em 29 de junho' },
  { word: 'PAULO', key: 'PAULO', definition: 'Apóstolo dos gentios' },
  { word: 'ANDRÉ', key: 'ANDRE', definition: 'Apóstolo, festa em 30 de novembro' },
  { word: 'TIAGO', key: 'TIAGO', definition: 'Apóstolo, festa em 25 de julho' },
  { word: 'LUCAS', key: 'LUCAS', definition: 'Evangelista, festa em 18 de outubro' },
  { word: 'MARIA', key: 'MARIA', definition: 'Mãe do Senhor' },
  { word: 'SIMÃO', key: 'SIMAO', definition: 'Apóstolo, festa em 28 de outubro' },
  { word: 'RITOS', key: 'RITOS', definition: 'Formas fixas da celebração' },

  // — segunda leva (ver BATCHES em ordle.ts: entradas novas vão no fim) —
  { word: 'JESUS', key: 'JESUS', definition: 'Nome do Senhor: "Deus salva"' },
  { word: 'HORAS', key: 'HORAS', definition: 'As horas do Ofício, da manhã às Completas' },
  { word: 'PRIMA', key: 'PRIMA', definition: 'Hora menor do Ofício, ao começo do dia' },
  { word: 'LIÇÃO', key: 'LICAO', definition: 'Leitura bíblica proclamada no Ofício' },
  { word: 'VERSO', key: 'VERSO', definition: 'Versículo dialogado entre quem preside e a assembleia' },
  { word: 'ÓLEOS', key: 'OLEOS', definition: 'Os santos óleos: crisma, catecúmenos e enfermos' },
  { word: 'MIRRA', key: 'MIRRA', definition: 'Resina ofertada pelos magos, sinal da sepultura' },
  { word: 'POMBA', key: 'POMBA', definition: 'Figura do Espírito Santo no batismo do Senhor' },
  { word: 'PEIXE', key: 'PEIXE', definition: 'Símbolo dos primeiros cristãos, sigla grega de Cristo' },
  { word: 'ÔMEGA', key: 'OMEGA', definition: 'Última letra grega: "o princípio e o fim"' },
  { word: 'ÁZIMO', key: 'AZIMO', definition: 'Pão sem fermento, o da Páscoa e o do altar' },
  { word: 'VINHA', key: 'VINHA', definition: 'Imagem do povo de Deus: "eu sou a videira"' },
  { word: 'NARDO', key: 'NARDO', definition: 'Perfume derramado sobre os pés do Senhor' },
  { word: 'COROA', key: 'COROA', definition: 'De espinhos na Paixão, de glória nos mártires' },
  { word: 'REINO', key: 'REINO', definition: 'O Reino de Deus, anunciado no Evangelho' },
  { word: 'BELÉM', key: 'BELEM', definition: 'Cidade da Natividade' },
  { word: 'SINAI', key: 'SINAI', definition: 'Monte da aliança e das tábuas da Lei' },
  { word: 'VERDE', key: 'VERDE', definition: 'Cor litúrgica do Tempo Comum' },
  { word: 'BENTO', key: 'BENTO', definition: 'Bento de Núrsia, pai do monaquismo ocidental' },
  { word: 'HILDA', key: 'HILDA', definition: 'Abadessa de Whitby, mestra de monges e de reis' },
  { word: 'CLARA', key: 'CLARA', definition: 'Clara de Assis, fundadora das clarissas' },
  { word: 'LÍDIA', key: 'LIDIA', definition: 'Vendedora de púrpura, primeira batizada na Europa' },
  { word: 'SILAS', key: 'SILAS', definition: 'Companheiro de Paulo nas viagens missionárias' },
  { word: 'MARTA', key: 'MARTA', definition: 'Irmã de Maria e de Lázaro, que acolheu o Senhor' },
  { word: 'MONJA', key: 'MONJA', definition: 'Religiosa de mosteiro' },
  { word: 'IRMÃO', key: 'IRMAO', definition: 'Religioso não ordenado de uma comunidade' },
  { word: 'FIÉIS', key: 'FIEIS', definition: 'A assembleia dos batizados' },
  { word: 'BURSA', key: 'BURSA', definition: 'Bolsa de tecido que guarda o corporal' },
  { word: 'VÊNIA', key: 'VENIA', definition: 'Inclinação reverente do corpo' },
  { word: 'TORRE', key: 'TORRE', definition: 'Onde ficam os sinos que chamam à oração' },
  { word: 'ANJOS', key: 'ANJOS', definition: 'Mensageiros de Deus, com quem a assembleia canta o Sanctus' },
  { word: 'NICHO', key: 'NICHO', definition: 'Vão na parede que abriga uma imagem' },
  { word: 'MURÇA', key: 'MURCA', definition: 'Capa curta de ombros, usada no coro' },
  { word: 'LIVRO', key: 'LIVRO', definition: 'O Livro de Oração Comum, que ordena o culto' },
  { word: 'TOCHA', key: 'TOCHA', definition: 'Vela alta levada na procissão' },
  { word: 'ANDOR', key: 'ANDOR', definition: 'Suporte em que se leva uma imagem em procissão' },
  { word: 'ÓBOLO', key: 'OBOLO', definition: 'Oferta pequena, como a da viúva do Evangelho' },
  { word: 'TEMPO', key: 'TEMPO', definition: 'Cada estação do ano litúrgico' },
  { word: 'FESTA', key: 'FESTA', definition: 'Celebração de grau maior no calendário' },
  { word: 'NEUMA', key: 'NEUMA', definition: 'Sinal do canto antigo, anterior à pauta musical' },
  { word: 'FILHO', key: 'FILHO', definition: 'A segunda pessoa da Trindade' },
  { word: 'EGITO', key: 'EGITO', definition: 'De onde o povo saiu na travessia do Êxodo' },
  { word: 'ELIAS', key: 'ELIAS', definition: 'Profeta arrebatado num carro de fogo' },
  { word: 'CEDRO', key: 'CEDRO', definition: 'Madeira nobre, a do Templo de Salomão' },
  { word: 'BRASA', key: 'BRASA', definition: 'Carvão aceso que queima o incenso no turíbulo' },

  // — terceira leva: só substantivos comuns, nenhum nome próprio —
  { word: 'ATRIL', key: 'ATRIL', definition: 'Suporte inclinado que sustenta o livro na leitura' },
  { word: 'PAUTA', key: 'PAUTA', definition: 'As linhas do canto, que vieram depois dos neumas' },
  { word: 'COROS', key: 'COROS', definition: 'De onde se canta o Ofício; também as ordens angélicas' },
  { word: 'PEDRA', key: 'PEDRA', definition: 'A angular, que os construtores rejeitaram' },
  { word: 'BARCA', key: 'BARCA', definition: 'Imagem antiga da Igreja, que atravessa o mar' },
  { word: 'REDES', key: 'REDES', definition: 'Deixadas na praia pelos primeiros discípulos' },
  { word: 'CHAVE', key: 'CHAVE', definition: 'Sinal do poder de abrir e fechar, confiado à Igreja' },
  { word: 'LANÇA', key: 'LANCA', definition: 'Abriu o lado do Senhor, de onde vieram sangue e água' },
  { word: 'LÍRIO', key: 'LIRIO', definition: 'Do campo, que não fia nem tece' },
  { word: 'SEARA', key: 'SEARA', definition: 'A messe é grande e os trabalhadores são poucos' },
  { word: 'MESSE', key: 'MESSE', definition: 'Colheita; imagem da missão confiada aos discípulos' },
  { word: 'FRUTO', key: 'FRUTO', definition: '"Fruto da terra e do trabalho humano", no ofertório' },
  { word: 'GRÃOS', key: 'GRAOS', definition: 'Os que caem na terra e morrem para dar muito fruto' },
  { word: 'BARRO', key: 'BARRO', definition: 'Somos barro nas mãos do oleiro' },
  { word: 'CHAMA', key: 'CHAMA', definition: 'Língua de fogo sobre os apóstolos em Pentecostes' },
  { word: 'LUZES', key: 'LUZES', definition: 'Acesas na Vigília, quando a igreja está às escuras' },
  { word: 'NUVEM', key: 'NUVEM', definition: 'Fumo do incenso; também a que guiou o povo no deserto' },
  { word: 'ÁGUAS', key: 'AGUAS', definition: 'As do batismo: morte e nascimento' },
  { word: 'MONTE', key: 'MONTE', definition: 'Lugar do encontro com Deus, do Sinai ao Calvário' },
  { word: 'MOEDA', key: 'MOEDA', definition: 'A perdida, procurada à luz da candeia' },
  { word: 'ENVIO', key: 'ENVIO', definition: 'O fim da celebração: "ide em paz"' },
  { word: 'GESTO', key: 'GESTO', definition: 'O corpo também ora: inclinar-se, ajoelhar, erguer as mãos' },
  { word: 'BEIJO', key: 'BEIJO', definition: 'Da paz, trocado antes da comunhão' },
  { word: 'FRADE', key: 'FRADE', definition: 'Religioso de ordem mendicante' },
  { word: 'TUMBA', key: 'TUMBA', definition: 'Sepultura; a que amanheceu vazia na Páscoa' },
  { word: 'BACIA', key: 'BACIA', definition: 'Do lavabo, em que se lavam as mãos antes do ofertório' },
  { word: 'CELAS', key: 'CELAS', definition: 'Os quartos dos monges no mosteiro' },
  { word: 'CICLO', key: 'CICLO', definition: 'A roda do ano litúrgico, que recomeça no Advento' },
  { word: 'VESTE', key: 'VESTE', definition: 'A branca do batismo, sinal da vida nova' },
  { word: 'CINTO', key: 'CINTO', definition: 'Cíngulo que prende a alva à cintura' },
  { word: 'ÁGAPE', key: 'AGAPE', definition: 'A refeição fraterna dos primeiros cristãos' },
  { word: 'LABOR', key: 'LABOR', definition: '"Ora et labora": o trabalho como forma de oração' },
  { word: 'ALMAS', key: 'ALMAS', definition: 'Os fiéis defuntos, lembrados no início de novembro' },
  { word: 'JUÍZO', key: 'JUIZO', definition: 'O final, esperado no fim dos tempos' },
  { word: 'COMUM', key: 'COMUM', definition: 'O dos Santos: textos para quem não tem próprio' },
  { word: 'PORTA', key: 'PORTA', definition: '"Eu sou a porta das ovelhas"' },
  { word: 'CEIFA', key: 'CEIFA', definition: 'A colheita do fim dos tempos, na parábola do joio' },
  { word: 'PAVIO', key: 'PAVIO', definition: 'O que fumega não será apagado, diz o profeta' },
  { word: 'PALHA', key: 'PALHA', definition: 'A da manjedoura, primeiro leito do Senhor' },
  { word: 'SONHO', key: 'SONHO', definition: 'Aviso de Deus na noite, como o que mandou fugir' },
]
